###
POST http://localhost/codechallenge-moolahgo-service/api/owner
Content-Type: application/json
Accept: application/json

{
  "name": "dudunk",
  "email": "haji.dudunk@gmail.com",
  "phone": "0987655"
}

###
POST http://localhost/codechallenge-moolahgo-service/api/process
Content-Type: application/json
Accept: application/json

{
  "referral_code": "DSNZLL"
}


###
GET http://localhost/codechallenge-moolahgo-service/api/process?referral_code=DSNZLL
Content-Type: application/json
Accept: application/json
